# Generated by Django 4.0.1 on 2022-07-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='objeto',
            fields=[
                ('idobjeto', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(blank=True, max_length=150, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('estatus', models.CharField(max_length=45)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('calificacionfinal', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('descargas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objeto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True, verbose_name='Telefono')),
                ('rfc', models.CharField(blank=True, max_length=200, null=True, verbose_name='RFC')),
                ('institucion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institucion')),
                ('departamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departamento')),
                ('estado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Estado')),
                ('carrera', models.CharField(blank=True, max_length=200, null=True, verbose_name='Carrera')),
                ('semestre', models.IntegerField(blank=True, null=True, verbose_name='Semestre')),
                ('rol', models.CharField(max_length=40, verbose_name='Rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=45)),
                ('idobjeto', models.ForeignKey(db_column='idobjeto', on_delete=django.db.models.deletion.DO_NOTHING, to='Objetivos.objeto')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='Objetivos.usuario')),
            ],
            options={
                'db_table': 'comentario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('idcalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('idobjeto', models.ForeignKey(db_column='idobjeto', on_delete=django.db.models.deletion.DO_NOTHING, to='Objetivos.objeto')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='Objetivos.usuario')),
            ],
            options={
                'db_table': 'calificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='autor',
            fields=[
                ('idautor', models.AutoField(primary_key=True, serialize=False)),
                ('idobjeto', models.ForeignKey(db_column='idobjeto', on_delete=django.db.models.deletion.DO_NOTHING, to='Objetivos.objeto')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='Objetivos.usuario')),
            ],
            options={
                'db_table': 'autor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('idobjeto', models.ForeignKey(db_column='idobjeto', on_delete=django.db.models.deletion.DO_NOTHING, to='Objetivos.objeto')),
            ],
            options={
                'db_table': 'area',
                'managed': True,
            },
        ),
    ]
