# Generated by Django 4.0.1 on 2022-07-19 18:56

import Objetivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objetivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='autor_principal',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='archivo',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=Objetivos.models.objeto_directory_path),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='estatus',
            field=models.CharField(default='activo', max_length=45),
        ),
    ]
