# Generated by Django 4.0.1 on 2022-08-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objetivos', '0004_objeto_autor_principal_nombre_alter_area_idobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='coautores',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
