# Generated by Django 4.1.1 on 2022-09-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objetivos', '0008_alter_arealist_nombre_alter_departamentolist_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealist',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departamentolist',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
