# Generated by Django 4.1.1 on 2022-09-08 13:43

import Objetivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objetivos', '0009_arealist_activo_departamentolist_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='fotos/DefaultUser.png', max_length=240, upload_to=Objetivos.models.imagen_directory_path, verbose_name='Foto de perfil'),
        ),
    ]
