# Generated by Django 4.1.1 on 2022-09-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objetivos', '0010_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='imagen_autor',
            field=models.ImageField(blank=True, default='fotos/DefaultUser.png', upload_to='', verbose_name='Foto de perfil'),
        ),
    ]
