# Generated by Django 4.1.1 on 2022-09-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Objetivos', '0011_objeto_imagen_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='autor_principal_nombre',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='imagen_autor',
        ),
    ]
